sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t downinalbion/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true downinalbion/docker-react npm run test